lang: en-US
title: Architect theme
description: Architect is a theme for GitHub Pages.
show_downloads: true
github:
  is_user_page: false
  zip_url: https://dsldsx.com/test.zip
  tar_url: https://dsldsx.com/test.tar.gz
google_analytics:
theme: jekyll-theme-architect
